"""Review a CV and cover letter against one specific job. Never invents a claim.

WHERE THIS DOES NOT GO - read before adding a data source
-----------------------------------------------------------
The obvious way to make a CV review feel authoritative is to say "recruiters at this
company look for X" or "other applicants typically Y". Neither claim would be true here,
because there is no legitimate source for either: Glassdoor's API closed to developers
in 2022 (see enrich.py's module docstring - this app already made that call once), and
no one publishes what "other applicants" wrote, nor should they. Inventing either would
be a fabricated statistic dressed up as insight, and the one thing worse than no feedback
is confident, wrong feedback.

What this module uses instead, all of it real:
  * the job's own posted text - title, full description, whatever it actually asks for
  * the candidate's own CV/profile skills, via cv.extract_skills - same matcher the rest
    of the app already uses for scoring, so a skill counted here is a skill counted there
  * the employer's own stated values, via interview.company_values - already fetched
    honestly elsewhere in this app; reused here, not refetched
  * real, verified-today CV and cover-letter guidance from actual career-advice sites
    (RESOURCES below) - each one checked with a live request before being hardcoded, the
    same discipline tools/discover_assessments.py uses for its interview-prep links

THE FACT-CHECKING PASS
-----------------------
Looking at how established open-source resume-review tools handle this (a project called
resume-helper on GitHub runs an adversarial Writer/Fact-Checker split, where the
Fact-Checker "compares resume claims against the original input to catch any invented
details" before anything reaches the user), the design here does the same thing natively
rather than as a second expensive model call: every piece of Claude-generated feedback
must cite the exact word or phrase it is grounded in, and _verify_evidence() checks that
citation against the actual source text before the suggestion is allowed through. A
suggestion whose evidence cannot be found gets dropped, not shown with a caveat - a
feedback tool that could ever tell someone "you claimed X" when they did not is worse
than a feedback tool with fewer things to say. This mirrors interview.py's _evidence_map,
which does the equivalent job for interview prep: every piece of advice tied to a
specific, checkable fact, never a vibe.

WHAT NEVER GETS STORED
-----------------------
The CV is read fresh from disk for the length of one request and never kept - CVProfile
has no field for it, on the same principle documented in cv.py. A cover letter, whether
generated by apply.py or pasted in by the user, is used in memory and returned in the
response; nothing here writes either one to the database, to profile.json, or to a log
line.
"""
from __future__ import annotations

import logging
import os
import re
from dataclasses import asdict, dataclass, field

from . import humanise
from .cv import CVProfile, extract_skills, read_document
from .models import Job

log = logging.getLogger("jobscout.review")

MODEL = "claude-opus-5"

# Checked live today (see the module docstring) before being hardcoded. If this list is
# ever edited, re-verify every URL with a real request first - a rotted link here is
# worse than no link, the same lesson interview.py's provider list already learned.
RESOURCES = [
    {"name": "CV sections explained", "for": "structure",
     "url": "https://nationalcareers.service.gov.uk/careers-advice/cv-sections",
     "what": "What each section of a CV is for, from the UK's National Careers Service."},
    {"name": "CVs and cover letters", "for": "general",
     "url": "https://www.prospects.ac.uk/careers-advice/cvs-and-cover-letters/",
     "what": "Prospects' full guide, aimed at students and graduates specifically."},
    {"name": "How to write a CV", "for": "structure",
     "url": "https://www.reed.co.uk/career-advice/how-to-write-a-cv/",
     "what": "Section-by-section walkthrough with UK formatting conventions."},
    {"name": "Cover letter examples", "for": "cover_letter",
     "url": "https://novoresume.com/career-blog/cover-letter-examples",
     "what": "Real worked examples across different situations, not just a template."},
    {"name": "31 cover letter tips", "for": "cover_letter",
     "url": "https://www.themuse.com/advice/how-to-write-a-cover-letter-31-tips-you-need-to-know",
     "what": "Specific, concrete tips rather than generic advice."},
]


@dataclass
class Review:
    job_id: str
    title: str
    company: str
    has_cv: bool = False
    cv_source: str = ""              # "cv" | "linkedin_export" | "linkedin_pdf" | ""
    matched_skills: list[str] = field(default_factory=list)
    missing_skills: list[dict] = field(default_factory=list)   # {skill, advice}
    structure: list[dict] = field(default_factory=list)        # {check, ok, note}
    cover_letter_checked: bool = False
    voice_tells: list[dict] = field(default_factory=list)
    voice_score: int = 100
    content_notes: list[dict] = field(default_factory=list)    # {note, evidence, source}
    resources: list[dict] = field(default_factory=list)
    engine: str = "rule-based"
    caveats: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return asdict(self)


# ------------------------------------------------------------------------- CV text
def cv_text_for(cfg) -> tuple[str, str]:
    """Read the CV fresh from disk. Returns (text, source-label). Never cached, never
    returned to a caller that might persist it - callers use it and let it go."""
    path = getattr(cfg.profile, "cv_path", "") or ""
    if not path:
        return "", ""
    try:
        return read_document(path), "cv"
    except (FileNotFoundError, ValueError, OSError) as exc:
        log.info("could not read CV for review: %s", exc)
        return "", ""


# --------------------------------------------------------------------- structure
_SECTION_WORDS = re.compile(
    r"\b(experience|employment|work history|education|qualifications|skills|"
    r"projects|profile|summary|about)\b", re.I)
_BULLET_LINE = re.compile(r"^\s*[••\-–*▪●○]\s*\S|^\s*\d+[.)]\s*\S")
_CONTACT_HINT = re.compile(r"[\w.+-]+@[\w-]+\.\w+|\b(?:\+?\d[\d\s().-]{7,}\d)\b")


def _structure_checks(cv_text: str) -> list[dict]:
    """Deterministic, defensible checks only - no claim this module cannot back up from
    the extracted text itself. Layout problems (a two-column CV an ATS reads out of
    order) cannot be detected from plain text with any confidence, so this does not
    pretend to - see the "reads jumbled" check below for the honest version of that."""
    checks = []
    words = cv_text.split()
    word_count = len(words)

    checks.append({
        "check": "Length", "ok": 150 <= word_count <= 1200,
        "note": (f"{word_count} words. " + (
            "A CV this short usually means sections are missing rather than that you "
            "have too little to say - most one-page CVs still run 300-600 words."
            if word_count < 150 else
            "Long enough that a recruiter skimming for 30 seconds may not reach the "
            "end - the most relevant points should be in the first third."
            if word_count > 1200 else
            "A reasonable length for a CV a recruiter will skim first."))})

    has_sections = bool(_SECTION_WORDS.search(cv_text))
    checks.append({
        "check": "Recognisable sections", "ok": has_sections,
        "note": ("Found section-style headings (education, experience, skills...)."
                 if has_sections else
                 "No section headings found (Education, Experience, Skills...) - if "
                 "your CV genuinely has them, this just means the extracted text lost "
                 "the formatting; if it does not, adding them helps both a human "
                 "skimmer and an ATS parser find things.")})

    bullet_lines = sum(1 for line in cv_text.splitlines() if _BULLET_LINE.match(line))
    checks.append({
        "check": "Bulleted content", "ok": bullet_lines >= 3,
        "note": (f"{bullet_lines} bullet-style lines found - easy to skim."
                 if bullet_lines >= 3 else
                 "Little or no bulleted content found. A CV that is mostly paragraphs "
                 "is harder to skim in the few seconds a recruiter actually gives it; "
                 "bullet points for individual achievements read faster.")})

    has_contact = bool(_CONTACT_HINT.search(cv_text[:600]))
    checks.append({
        "check": "Contact details near the top", "ok": has_contact,
        "note": ("Found something that reads as an email or phone number near the top."
                 if has_contact else
                 "Nothing that reads as an email or phone number in the first few "
                 "lines - worth checking it is there and not buried in an image or a "
                 "header/footer, which some parsers skip entirely.")})

    # The closest this module gets to a layout warning, and it is phrased as what it
    # actually is: a proxy, not a verdict. A genuinely multi-column CV extracts as
    # short, disconnected fragments in an odd order; this counts how much of the text
    # looks like that rather than claiming to see the layout itself.
    #
    # Section headers, a name, and short one-line dates are ALSO short - a well-formed
    # CV legitimately has several ("EDUCATION", "John Smith", "2022-2026"), and the
    # first version of this check flagged exactly those, contradicting the
    # "Recognisable sections" check three lines above it, which praises the same
    # headers this one was punishing. Excluded here rather than counted against it.
    lines = [l.strip() for l in cv_text.splitlines() if l.strip()]
    short = [l for l in lines if 0 < len(l.split()) <= 2]
    fragment_lines = [l for l in short
                      if not _SECTION_WORDS.search(l) and not l.isupper()
                      and not re.match(r"^[A-Z][a-z]+\s+[A-Z][a-z]+$", l)]
    fragment_ratio = len(fragment_lines) / len(lines) if lines else 0
    checks.append({
        "check": "Reads in a sensible order", "ok": fragment_ratio < 0.35,
        "note": ("The extracted text reads as ordinary sentences and phrases."
                 if fragment_ratio < 0.35 else
                 "A lot of short, disconnected fragments came out of this file. That "
                 "can be entirely normal for a CV, but it is also what a multi-column "
                 "layout looks like once the columns get read left-to-right, top-to-"
                 "bottom instead of column-by-column - the exact way some ATS systems "
                 "parse a CV. If your layout uses columns, a single-column version is "
                 "the safer bet for anything that goes through automated screening.")})

    return checks


# ----------------------------------------------------------------------- skill fit
def _skill_fit(job: Job, profile: CVProfile | None,
              cv_text: str) -> tuple[list[str], list[dict]]:
    """Same matcher the rest of the app scores with, so a skill counted here is a skill
    counted on the job row - no separate, disagreeing opinion about what "matches"."""
    posting_skills = set(job.matched_skills or []) | set(job.missing_skills or [])
    if not posting_skills:
        posting_skills = set(extract_skills(f"{job.title} {job.description}"))

    mine = set(profile.skills) if profile else set()
    if cv_text:
        mine |= set(extract_skills(cv_text))

    matched = sorted(posting_skills & mine)
    missing = []
    for skill in sorted(posting_skills - mine):
        missing.append({
            "skill": skill,
            "advice": (f"The posting asks for {skill} and it is not showing up in what "
                      f"you have linked. If you have used it - coursework, a project, "
                      f"a previous role - name it explicitly; a skill you have but "
                      f"never wrote down cannot be matched by anything, human or "
                      f"automated. If you genuinely have not, better to leave it out "
                      f"than claim it - bluffing this is how interviews end."),
        })
    return matched, missing[:10]


# --------------------------------------------------------------- fact-checking pass
def _normalise(text: str) -> str:
    return re.sub(r"\s+", " ", text.lower()).strip()


def _verify_evidence(evidence: str, source_texts: dict[str, str]) -> str | None:
    """Does this cited snippet actually appear in the source it claims to be from?

    Returns the source key it was verified against, or None if it cannot be found
    anywhere - the caller drops the suggestion in that case. Whitespace/case-insensitive
    because Claude will not reproduce a quote byte-for-byte, but a genuine citation
    still has to appear as a real substring once both sides are normalised the same way;
    a paraphrase or an invention will not.
    """
    if not evidence or len(evidence.strip()) < 3:
        return None
    needle = _normalise(evidence)
    for source, text in source_texts.items():
        if text and needle in _normalise(text):
            return source
    return None


def _claude_review(job: Job, profile: CVProfile | None, cv_text: str,
                   cover_letter: str, values: list[str]) -> dict | None:
    """Ask Claude for qualitative feedback, every point evidence-cited against the real
    source text. Returns None when no key is configured - the deterministic checks above
    already make the feature fully usable without one."""
    if not os.environ.get("ANTHROPIC_API_KEY"):
        return None
    try:
        import anthropic
    except ImportError:
        return None
    if not cv_text and not cover_letter:
        return None

    tool = {
        "name": "cv_review",
        "description": "Feedback on a CV and/or cover letter for one specific job.",
        "input_schema": {
            "type": "object",
            "properties": {
                "notes": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "note": {"type": "string",
                                     "description": "One piece of concrete feedback."},
                            "source": {"type": "string", "enum": ["cv", "letter", "job"],
                                       "description": "Which text the evidence below is "
                                                      "quoted from."},
                            "evidence": {"type": "string",
                                         "description": "The exact short phrase, copied "
                                                        "verbatim from that source text, "
                                                        "that this note is grounded in. "
                                                        "Never a paraphrase."},
                        },
                        "required": ["note", "source", "evidence"],
                    },
                },
            },
            "required": ["notes"],
        },
    }

    parts = [f"ROLE: {job.title}\nCOMPANY: {job.company}\n"
            f"JOB ADVERT:\n{job.description[:3500]}"]
    if values:
        parts.append(f"\nTHE EMPLOYER'S OWN STATED VALUES: {', '.join(values)}")
    if cv_text:
        parts.append(f"\nCV TEXT:\n{cv_text[:4000]}")
    if cover_letter:
        parts.append(f"\nCOVER LETTER DRAFT:\n{cover_letter[:2500]}")

    prompt = "\n".join(parts) + f"""

Give up to 8 specific, useful notes on how well the CV and/or cover letter fit THIS
job - not generic CV advice, which is available elsewhere and is not what this is for.
Look for: skills or experience the job asks for that are in the CV but easy to miss
(buried, unlabelled, in the wrong section); places the cover letter is generic rather
than specific to this employer; claims made without a number or concrete result attached;
anywhere the stated values above could be answered with something already in the CV but
is not currently used that way.

For every note, "evidence" must be an exact, verbatim short phrase (a few words, copied
character-for-character) from the CV, the letter, or the job advert - whichever the note
is about. Do not paraphrase, summarise, or invent a quote. A note whose evidence cannot
be found verbatim in the source will be discarded before the person ever sees it, so an
invented quote wastes the note entirely - ground every one for real.

Never invent an achievement, employer, project or number the source text does not
contain. Never claim to know what "recruiters at this company" or "other applicants" do
- you have no legitimate source for that and neither does this tool.

{humanise.VOICE_RULES}"""

    try:
        client = anthropic.Anthropic()
        response = client.messages.create(
            model=MODEL, max_tokens=2000,
            tools=[tool], tool_choice={"type": "tool", "name": "cv_review"},
            messages=[{"role": "user", "content": prompt}])
        for block in response.content:
            if getattr(block, "type", "") == "tool_use":
                return block.input
    except Exception as exc:
        log.warning("Claude unavailable for the CV/letter review: %s", exc)
    return None


# --------------------------------------------------------------------------- build
def build_review(job: Job, profile: CVProfile | None, cfg,
                 company_info: dict | None = None, cover_letter: str = "",
                 use_model: bool = True) -> Review:
    """Everything worth knowing about how a CV and cover letter fit this one job."""
    cv_text, cv_source = cv_text_for(cfg)
    if not cv_text and profile and profile.source in ("linkedin_export", "linkedin_pdf"):
        cv_source = profile.source

    matched, missing = _skill_fit(job, profile, cv_text)
    review = Review(
        job_id=job.id, title=job.title, company=job.company,
        has_cv=bool(cv_text or (profile and profile.skills)),
        cv_source=cv_source,
        matched_skills=matched, missing_skills=missing,
        structure=_structure_checks(cv_text) if cv_text else [],
        cover_letter_checked=bool(cover_letter),
        resources=RESOURCES,
    )

    if not cv_text:
        review.caveats.append(
            "No CV file is linked (set profile.cv_path, or import your LinkedIn on the "
            "Profile tab), so structure and wording checks are unavailable. Skill "
            "matching below still uses whatever skills your profile already has.")

    if cover_letter:
        review.voice_tells = humanise.tells(cover_letter)[:6]
        review.voice_score = humanise.score(cover_letter)

    values = []
    if company_info and company_info.get("website"):
        try:
            from .interview import company_values
            values = company_values(job.company, company_info["website"])["values"]
        except Exception as exc:
            log.info("could not read company values for the review: %s", exc)

    generated = _claude_review(job, profile, cv_text, cover_letter, values) if use_model else None
    if generated:
        sources = {"cv": cv_text, "letter": cover_letter, "job": job.description}
        kept = []
        dropped = 0
        for item in generated.get("notes", []):
            note, evidence = item.get("note", ""), item.get("evidence", "")
            if not note:
                continue
            verified_source = _verify_evidence(evidence, sources)
            if verified_source is None:
                dropped += 1
                continue
            kept.append({"note": humanise.soften(note), "evidence": evidence,
                        "source": verified_source})
        review.content_notes = kept
        review.engine = MODEL
        if dropped:
            log.info("CV review: dropped %d unverifiable note(s) from %s", dropped, MODEL)

    return review
